2025-07-24 11:09:46,227 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:09:46,229 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 11:10:30,042 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-24 11:20:09,095 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
2025-07-24 11:20:09,095 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-24 11:20:09,097 INFO werkzeug:  * Restarting with stat
2025-07-24 11:20:09,398 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:20:09,398 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 11:20:11,183 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:20:11] "GET /mathSolve/login HTTP/1.1" 200 -
2025-07-24 11:20:25,594 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-24 11:20:25,732 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-24 11:20:25,736 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:20:25] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-24 11:20:25,842 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:20:25] "GET /mathSolve/calculator HTTP/1.1" 200 -
2025-07-24 11:26:29,667 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-24 11:26:29,741 INFO werkzeug:  * Restarting with stat
2025-07-24 11:27:53,258 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
2025-07-24 11:27:53,259 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-24 11:27:53,260 INFO werkzeug:  * Restarting with stat
2025-07-24 11:27:53,617 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:27:53,619 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:28:02,171 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-24 11:28:02,295 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-24 11:28:02,301 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:28:02] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-24 11:28:02,387 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:28:02] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 11:35:57,105 INFO werkzeug:  * Detected change in '/app/model/operation_model.py', reloading
2025-07-24 11:35:57,165 INFO werkzeug:  * Restarting with stat
2025-07-24 11:35:57,645 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:35:57,647 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:36:04,006 INFO werkzeug:  * Detected change in '/app/model/operation_model.py', reloading
2025-07-24 11:36:04,048 INFO werkzeug:  * Restarting with stat
2025-07-24 11:36:04,344 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:36:04,345 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:36:13,788 INFO werkzeug:  * Detected change in '/app/model/operation_model.py', reloading
2025-07-24 11:36:13,822 INFO werkzeug:  * Restarting with stat
2025-07-24 11:36:14,102 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:36:14,103 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:36:16,259 INFO werkzeug:  * Detected change in '/app/model/operation_model.py', reloading
2025-07-24 11:36:16,300 INFO werkzeug:  * Restarting with stat
2025-07-24 11:36:16,599 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:36:16,599 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:45:37,728 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:45:37,788 INFO werkzeug:  * Restarting with stat
2025-07-24 11:45:38,243 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:45:38,244 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:45:44,653 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:45:44,748 INFO werkzeug:  * Restarting with stat
2025-07-24 11:45:45,334 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:45:45,335 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:45:52,430 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:45:52,688 INFO werkzeug:  * Restarting with stat
2025-07-24 11:49:19,786 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
2025-07-24 11:49:19,786 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-24 11:49:19,788 INFO werkzeug:  * Restarting with stat
2025-07-24 11:49:20,156 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:49:20,157 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:49:26,434 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:49:26] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 11:49:30,303 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:49:30] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:50:14,417 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:50:14] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:50:49,890 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:50:50,002 INFO werkzeug:  * Restarting with stat
2025-07-24 11:50:50,736 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:50:50,738 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:50:50,846 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:50:50,923 INFO werkzeug:  * Restarting with stat
2025-07-24 11:50:51,402 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:50:51,404 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:50:52,570 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:50:52,640 INFO werkzeug:  * Restarting with stat
2025-07-24 11:50:53,091 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:50:53,091 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:50:56,370 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:50:56,446 INFO werkzeug:  * Restarting with stat
2025-07-24 11:50:56,853 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:50:56,854 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:50:59,074 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:50:59,153 INFO werkzeug:  * Restarting with stat
2025-07-24 11:50:59,611 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:50:59,612 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:51:03,968 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:51:04,077 INFO werkzeug:  * Restarting with stat
2025-07-24 11:51:04,495 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:51:04,495 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:51:15,202 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:51:15,301 INFO werkzeug:  * Restarting with stat
2025-07-24 11:51:15,734 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:51:15,735 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:51:40,867 ERROR root: Error in power calculation
Traceback (most recent call last):
  File "/app/controller/math_controller.py", line 14, in power
    operation_model.insert_operation(db_connection.get_connection(), db_connection.get_cursor(), 'power', {'base': base, 'exponent': exponent}, formatted)
AttributeError: module 'model.db_connection' has no attribute 'get_cursor'
2025-07-24 11:51:40,875 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:51:40] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:52:57,936 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:52:58,030 INFO werkzeug:  * Restarting with stat
2025-07-24 11:52:58,493 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:52:58,494 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:53:03,242 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:53:03] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 11:53:05,975 ERROR root: Error in power calculation
Traceback (most recent call last):
  File "/app/controller/math_controller.py", line 14, in power
    operation_model.insert_operation(db_connection.get_connection(), db_connection.get_connection.get_cursor(), 'power', {'base': base, 'exponent': exponent}, formatted)
AttributeError: 'function' object has no attribute 'get_cursor'
2025-07-24 11:53:05,981 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:53:05] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:53:45,068 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:53:45,138 INFO werkzeug:  * Restarting with stat
2025-07-24 11:53:45,544 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:53:45,548 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:53:48,254 ERROR root: Error in power calculation
Traceback (most recent call last):
  File "/app/controller/math_controller.py", line 14, in power
    operation_model.insert_operation(db_connection.get_connection(), db_connection.get_connection.cursor(), 'power', {'base': base, 'exponent': exponent}, formatted)
AttributeError: 'function' object has no attribute 'cursor'
2025-07-24 11:53:48,261 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:53:48] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:53:51,925 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:53:51] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 11:53:53,871 ERROR root: Error in power calculation
Traceback (most recent call last):
  File "/app/controller/math_controller.py", line 14, in power
    operation_model.insert_operation(db_connection.get_connection(), db_connection.get_connection.cursor(), 'power', {'base': base, 'exponent': exponent}, formatted)
AttributeError: 'function' object has no attribute 'cursor'
2025-07-24 11:53:53,875 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:53:53] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:54:05,033 ERROR root: Error in power calculation
Traceback (most recent call last):
  File "/app/controller/math_controller.py", line 14, in power
    operation_model.insert_operation(db_connection.get_connection(), db_connection.get_connection.cursor(), 'power', {'base': base, 'exponent': exponent}, formatted)
AttributeError: 'function' object has no attribute 'cursor'
2025-07-24 11:54:05,037 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:54:05] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:55:18,600 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:55:18,861 INFO werkzeug:  * Restarting with stat
2025-07-24 11:55:19,471 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:55:19,473 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:55:22,131 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:55:22] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 11:55:24,359 ERROR root: Error in power calculation
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/cursor_cext.py", line 310, in execute
    if not self._connection or self._connection.is_closed():
ReferenceError: weakly-referenced object no longer exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/controller/math_controller.py", line 14, in power
    operation_model.insert_operation(db_connection.get_connection(), db_connection.get_connection().cursor(), 'power', {'base': base, 'exponent': exponent}, formatted)
  File "/app/model/operation_model.py", line 13, in insert_operation
    cursor.execute(query, (endpoint, input_data, result))
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/cursor_cext.py", line 313, in execute
    raise ProgrammingError("Cursor is not connected", 2055) from err
mysql.connector.errors.ProgrammingError: 2055: Cursor is not connected
2025-07-24 11:55:24,371 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:55:24] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:56:23,458 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:56:23,549 INFO werkzeug:  * Restarting with stat
2025-07-24 11:56:24,035 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:56:24,036 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:56:26,285 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:56:26,358 INFO werkzeug:  * Restarting with stat
2025-07-24 11:56:26,784 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:56:26,785 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:56:29,055 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:56:29] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 11:56:30,960 ERROR root: Error in power calculation
Traceback (most recent call last):
  File "/app/controller/math_controller.py", line 16, in power
    operation_model.insert_operation(conn, cursor, 'power', {'base': base, 'exponent': exponent}, formatted)
  File "/app/model/operation_model.py", line 13, in insert_operation
    cursor.execute(query, (endpoint, input_data, result))
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/cursor_cext.py", line 328, in execute
    prepared = self._connection.prepare_for_mysql(params)
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 943, in prepare_for_mysql
    result = self._cmysql.convert_to_mysql(*params)
_mysql_connector.MySQLInterfaceError: Python type dict cannot be converted
2025-07-24 11:56:30,971 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:56:30] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 11:57:54,614 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:57:54,789 INFO werkzeug:  * Restarting with stat
2025-07-24 11:57:55,538 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:57:55,539 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:58:08,347 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:58:08,420 INFO werkzeug:  * Restarting with stat
2025-07-24 11:58:08,883 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:58:08,884 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:58:23,733 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 11:58:23,833 INFO werkzeug:  * Restarting with stat
2025-07-24 11:58:24,384 WARNING werkzeug:  * Debugger is active!
2025-07-24 11:58:24,385 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 11:58:26,893 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:58:26] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 11:58:29,432 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 11:58:29] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 12:08:26,321 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:08:26] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 12:22:14,191 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-24 12:22:14,261 INFO werkzeug:  * Restarting with stat
2025-07-24 12:22:14,908 WARNING werkzeug:  * Debugger is active!
2025-07-24 12:22:14,910 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 12:27:46,936 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 12:27:47,034 INFO werkzeug:  * Restarting with stat
2025-07-24 12:27:47,668 WARNING werkzeug:  * Debugger is active!
2025-07-24 12:27:47,669 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 12:27:59,292 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 12:27:59,335 INFO werkzeug:  * Restarting with stat
2025-07-24 12:27:59,642 WARNING werkzeug:  * Debugger is active!
2025-07-24 12:27:59,642 INFO werkzeug:  * Debugger PIN: 640-611-084
2025-07-24 12:28:19,759 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:28:19] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 12:28:23,718 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:28:23] "POST /mathSolve/api/fibonacci HTTP/1.1" 200 -
2025-07-24 12:28:31,438 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:28:31] "POST /mathSolve/api/factorial HTTP/1.1" 200 -
2025-07-24 12:28:37,008 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:28:37] "POST /mathSolve/api/factorial HTTP/1.1" 200 -
2025-07-24 12:40:52,871 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
2025-07-24 12:40:52,873 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-24 12:40:52,876 INFO werkzeug:  * Restarting with stat
2025-07-24 12:40:53,401 WARNING werkzeug:  * Debugger is active!
2025-07-24 12:40:53,404 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 12:40:57,177 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:40:57] "[35m[1mGET /mathSolve/calculator HTTP/1.1[0m" 500 -
2025-07-24 12:40:57,224 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:40:57] "[36mGET /mathSolve/calculator?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-07-24 12:40:57,238 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:40:57] "[36mGET /mathSolve/calculator?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-07-24 12:40:57,272 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:40:57] "GET /mathSolve/calculator?__debugger__=yes&cmd=resource&f=console.png&s=M6h1crew1MhKboxm4HmZ HTTP/1.1" 200 -
2025-07-24 12:40:57,348 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:40:57] "[36mGET /mathSolve/calculator?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-07-24 12:41:38,757 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:41:38] "GET /mathSolve/login HTTP/1.1" 200 -
2025-07-24 12:41:46,417 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-24 12:41:46,536 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-24 12:41:46,539 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:41:46] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-24 12:41:46,605 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:41:46] "GET /mathSolve/calculator HTTP/1.1" 200 -
2025-07-24 12:41:50,207 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:41:50] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 12:41:57,899 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:41:57] "POST /mathSolve/api/fibonacci HTTP/1.1" 200 -
2025-07-24 12:41:59,077 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 12:41:59] "POST /mathSolve/api/factorial HTTP/1.1" 200 -
2025-07-24 14:06:43,512 INFO werkzeug:  * Detected change in '/app/controller/login_controller.py', reloading
2025-07-24 14:06:43,600 INFO werkzeug:  * Restarting with stat
2025-07-24 14:06:44,255 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:06:44,256 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:06:52,737 INFO werkzeug:  * Detected change in '/app/controller/login_controller.py', reloading
2025-07-24 14:06:52,777 INFO werkzeug:  * Restarting with stat
2025-07-24 14:06:53,132 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:06:53,133 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:06:55,329 INFO werkzeug:  * Detected change in '/app/controller/login_controller.py', reloading
2025-07-24 14:06:55,379 INFO werkzeug:  * Restarting with stat
2025-07-24 14:09:40,199 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
2025-07-24 14:09:40,200 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-24 14:09:40,201 INFO werkzeug:  * Restarting with stat
2025-07-24 14:09:40,556 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:09:40,557 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:09:47,376 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:47] "[35m[1mGET /mathSolve/calculator HTTP/1.1[0m" 500 -
2025-07-24 14:09:47,400 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:47] "[36mGET /mathSolve/calculator?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-07-24 14:09:47,406 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:47] "[36mGET /mathSolve/calculator?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-07-24 14:09:47,448 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:47] "GET /mathSolve/calculator?__debugger__=yes&cmd=resource&f=console.png&s=3oL0kwyefkCJfjQF4KDJ HTTP/1.1" 200 -
2025-07-24 14:09:47,492 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:47] "[36mGET /mathSolve/calculator?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2025-07-24 14:09:49,876 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:49] "GET /mathSolve/login HTTP/1.1" 200 -
2025-07-24 14:09:55,891 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-24 14:09:55,926 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:55] "[35m[1mPOST /mathSolve/login HTTP/1.1[0m" 500 -
2025-07-24 14:09:55,947 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:55] "GET /mathSolve/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-07-24 14:09:55,954 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:55] "GET /mathSolve/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-07-24 14:09:55,975 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:55] "GET /mathSolve/login?__debugger__=yes&cmd=resource&f=console.png&s=3oL0kwyefkCJfjQF4KDJ HTTP/1.1" 200 -
2025-07-24 14:09:56,015 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:09:56] "GET /mathSolve/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-07-24 14:10:03,831 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-24 14:10:03,837 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:10:03] "[35m[1mPOST /mathSolve/login HTTP/1.1[0m" 500 -
2025-07-24 14:10:03,851 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:10:03] "[36mGET /mathSolve/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-07-24 14:10:03,854 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:10:03] "[36mGET /mathSolve/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-07-24 14:10:03,878 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:10:03] "[36mGET /mathSolve/login?__debugger__=yes&cmd=resource&f=console.png&s=3oL0kwyefkCJfjQF4KDJ HTTP/1.1[0m" 304 -
2025-07-24 14:11:09,496 INFO werkzeug:  * Detected change in '/app/model/user_model.py', reloading
2025-07-24 14:11:09,549 INFO werkzeug:  * Restarting with stat
2025-07-24 14:11:10,065 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:11:10,066 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:11:17,017 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-24 14:11:17,120 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-24 14:11:17,145 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:11:17] "[35m[1mPOST /mathSolve/login HTTP/1.1[0m" 500 -
2025-07-24 14:11:17,159 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:11:17] "[36mGET /mathSolve/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-07-24 14:11:17,161 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:11:17] "[36mGET /mathSolve/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-07-24 14:11:17,169 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:11:17] "GET /mathSolve/login?__debugger__=yes&cmd=resource&f=console.png&s=VyskqIU1VdLcTZfLbI0a HTTP/1.1" 200 -
2025-07-24 14:11:57,085 INFO werkzeug:  * Detected change in '/app/controller/login_controller.py', reloading
2025-07-24 14:11:57,139 INFO werkzeug:  * Restarting with stat
2025-07-24 14:11:57,505 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:11:57,505 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:12:06,256 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-24 14:12:06,360 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-24 14:12:06,363 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:12:06] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-24 14:12:06,439 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:12:06] "GET /mathSolve/calculator HTTP/1.1" 200 -
2025-07-24 14:13:15,822 INFO werkzeug:  * Detected change in '/app/utils/auth_utils.py', reloading
2025-07-24 14:13:15,986 INFO werkzeug:  * Restarting with stat
2025-07-24 14:13:35,413 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
2025-07-24 14:13:35,414 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-24 14:13:35,416 INFO werkzeug:  * Restarting with stat
2025-07-24 14:13:35,878 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:13:35,880 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:14:04,510 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 14:14:04,583 INFO werkzeug:  * Restarting with stat
2025-07-24 14:14:05,040 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:14:05,041 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:14:14,720 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-24 14:14:14,793 INFO werkzeug:  * Restarting with stat
2025-07-24 14:20:33,488 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
2025-07-24 14:20:33,488 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-24 14:20:33,490 INFO werkzeug:  * Restarting with stat
2025-07-24 14:20:33,931 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:20:33,932 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:21:38,848 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-24 14:21:38,998 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-24 14:21:39,003 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:21:39] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-24 14:21:39,078 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:21:39] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 14:21:48,521 ERROR root: Error in power calculation
Traceback (most recent call last):
  File "/app/controller/math_controller.py", line 25, in power
    operation_model.insert_operation(self.db, self.cursor, 'power', input_data_json, formatted, user_id)
  File "/app/model/operation_model.py", line 13, in insert_operation
    cursor.execute(query, (endpoint, input_data, result, user_id))
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/cursor_cext.py", line 335, in execute
    raise ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2025-07-24 14:21:48,530 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:21:48] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-24 14:22:53,078 INFO werkzeug:  * Detected change in '/app/model/operation_model.py', reloading
2025-07-24 14:22:53,173 INFO werkzeug:  * Restarting with stat
2025-07-24 14:22:53,630 WARNING werkzeug:  * Debugger is active!
2025-07-24 14:22:53,630 INFO werkzeug:  * Debugger PIN: 420-790-205
2025-07-24 14:22:58,971 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:22:58] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-24 14:23:01,627 INFO werkzeug: 192.168.143.2 - - [24/Jul/2025 14:23:01] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-25 07:38:47,716 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
2025-07-25 07:38:47,717 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 07:38:47,718 INFO werkzeug:  * Restarting with stat
2025-07-25 07:38:48,092 WARNING werkzeug:  * Debugger is active!
2025-07-25 07:38:48,096 INFO werkzeug:  * Debugger PIN: 201-974-333
2025-07-25 07:38:57,231 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:38:57] "[33mGET /welcome HTTP/1.1[0m" 404 -
2025-07-25 07:38:57,361 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:38:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-25 07:39:07,303 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:39:07] "[36mGET /mathSolve/welcome HTTP/1.1[0m" 304 -
2025-07-25 07:39:09,330 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:39:09] "GET /mathSolve/login HTTP/1.1" 200 -
2025-07-25 07:39:14,256 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-25 07:39:14,386 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-25 07:39:14,390 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:39:14] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-25 07:39:14,456 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:39:14] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 07:39:17,316 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:39:17] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-25 07:39:30,384 INFO flask_caching: Cache used for key: /mathSolve/api/powerbcd8b0c2eb1fce714eab6cef0d771acc
2025-07-25 07:39:30,385 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:39:30] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-25 07:39:42,197 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:39:42] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-07-25 07:42:04,259 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:42:04] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-25 07:42:06,191 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:42:06] "POST /mathSolve/api/fibonacci HTTP/1.1" 200 -
2025-07-25 07:42:07,029 INFO flask_caching: Cache used for key: /mathSolve/api/fibonaccibcd8b0c2eb1fce714eab6cef0d771acc
2025-07-25 07:42:07,030 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:42:07] "POST /mathSolve/api/fibonacci HTTP/1.1" 200 -
2025-07-25 07:42:09,072 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:42:09] "POST /mathSolve/api/factorial HTTP/1.1" 200 -
2025-07-25 07:46:31,787 INFO werkzeug:  * Detected change in '/app/controller/math_controller.py', reloading
2025-07-25 07:46:31,899 INFO werkzeug:  * Restarting with stat
2025-07-25 07:47:16,340 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
2025-07-25 07:47:16,341 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 07:47:16,343 INFO werkzeug:  * Restarting with stat
2025-07-25 07:47:16,748 WARNING werkzeug:  * Debugger is active!
2025-07-25 07:47:16,748 INFO werkzeug:  * Debugger PIN: 376-664-055
2025-07-25 07:47:21,789 INFO root: Se execută calculul power (NU din cache)
2025-07-25 07:47:21,844 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:47:21] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-25 07:47:25,943 INFO flask_caching: Cache used for key: /mathSolve/api/powerbcd8b0c2eb1fce714eab6cef0d771acc
2025-07-25 07:47:25,945 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:47:25] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-25 07:47:36,777 INFO flask_caching: Cache used for key: /mathSolve/api/powerbcd8b0c2eb1fce714eab6cef0d771acc
2025-07-25 07:47:36,778 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:47:36] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-25 07:50:37,992 INFO root: Se execută calculul power (NU din cache)
2025-07-25 07:50:38,034 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 07:50:38] "POST /mathSolve/api/power HTTP/1.1" 200 -
2025-07-25 08:57:13,499 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
2025-07-25 08:57:13,500 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 08:57:13,501 INFO werkzeug:  * Restarting with stat
2025-07-25 08:57:13,882 WARNING werkzeug:  * Debugger is active!
2025-07-25 08:57:13,883 INFO werkzeug:  * Debugger PIN: 201-974-333
2025-07-25 08:58:19,656 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 08:58:19,717 INFO werkzeug:  * Restarting with stat
2025-07-25 09:00:23,256 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
2025-07-25 09:00:23,257 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 09:00:23,258 INFO werkzeug:  * Restarting with stat
2025-07-25 09:00:23,638 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:00:23,651 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:00:23,652 INFO werkzeug:  * Debugger PIN: 376-664-055
2025-07-25 09:00:40,573 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:00:40] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:01:22,246 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:01:22,318 INFO werkzeug:  * Restarting with stat
2025-07-25 09:01:22,730 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:01:22,742 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:01:22,743 INFO werkzeug:  * Debugger PIN: 376-664-055
2025-07-25 09:01:24,550 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:01:24] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:01:24,582 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:01:24] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-25 09:01:34,737 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:01:34] "[33mGET /welcome HTTP/1.1[0m" 404 -
2025-07-25 09:01:42,040 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:01:42] "[36mGET /mathSolve/welcome HTTP/1.1[0m" 304 -
2025-07-25 09:01:46,593 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:01:46] "[33mGET /mathSolve/metrics HTTP/1.1[0m" 404 -
2025-07-25 09:01:57,507 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:01:57] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:02:21,415 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:02:21,467 INFO werkzeug:  * Restarting with stat
2025-07-25 09:02:21,852 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:03:16,516 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2025-07-25 09:03:16,517 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 09:03:16,518 INFO werkzeug:  * Restarting with stat
2025-07-25 09:03:16,999 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:03:17,010 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:03:17,013 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:03:24,895 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:03:24] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:03:25,654 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:03:25] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:03:26,478 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:03:26] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:03:42,630 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:03:42] "[33mGET /matrics HTTP/1.1[0m" 404 -
2025-07-25 09:03:44,250 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:03:44,320 INFO werkzeug:  * Restarting with stat
2025-07-25 09:03:44,722 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:03:44,733 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:03:44,733 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:03:49,925 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:03:49] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:03:56,320 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:03:56,375 INFO werkzeug:  * Restarting with stat
2025-07-25 09:03:56,771 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:03:56,781 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:03:56,782 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:03:59,366 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:03:59] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:03:59,393 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:03:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-25 09:04:00,337 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:04:00] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:04:00,357 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:04:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-25 09:04:00,787 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:04:00] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:04:00,807 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:04:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-25 09:04:01,595 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:04:01] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:04:01,623 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:04:01] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-25 09:04:12,279 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:04:12] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:06:30,881 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2025-07-25 09:06:30,882 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 09:06:30,882 INFO werkzeug:  * Restarting with stat
2025-07-25 09:06:31,260 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:06:31,269 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:06:31,270 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:06:33,042 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:06:33] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:06:33,887 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:06:33] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:06:34,326 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:06:34] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:06:41,084 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:06:41] "[36mGET /mathSolve/welcome HTTP/1.1[0m" 304 -
2025-07-25 09:06:42,421 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:06:42] "GET /mathSolve/login HTTP/1.1" 200 -
2025-07-25 09:06:47,811 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-25 09:06:47,931 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-25 09:06:47,934 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:06:47] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-25 09:06:48,000 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:06:48] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 09:06:54,213 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:06:54] "[33mGET /matrics HTTP/1.1[0m" 404 -
2025-07-25 09:07:14,105 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:07:14] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:07:54,078 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:07:54,145 INFO werkzeug:  * Restarting with stat
2025-07-25 09:07:54,678 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:07:54,694 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:07:54,695 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:08:06,700 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:08:06] "[33mGET /mathSolve/metrics HTTP/1.1[0m" 404 -
2025-07-25 09:13:27,681 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:13:27,737 INFO werkzeug:  * Restarting with stat
2025-07-25 09:13:28,104 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:13:28,114 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:13:28,115 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:13:39,254 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:13:39] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 09:13:48,070 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:13:48] "[33mGET /metrics HTTP/1.1[0m" 404 -
2025-07-25 09:14:57,970 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:14:58,018 INFO werkzeug:  * Restarting with stat
2025-07-25 09:14:58,428 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:14:58,437 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:14:58,438 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:15:08,936 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:15:08,980 INFO werkzeug:  * Restarting with stat
2025-07-25 09:15:09,402 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:15:09,410 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:15:09,411 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:15:17,589 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:15:17] "GET /mathSolve/metrics HTTP/1.1" 200 -
2025-07-25 09:16:57,207 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:16:57,258 INFO werkzeug:  * Restarting with stat
2025-07-25 09:16:57,604 DEBUG main: Metrics are disabled when run in the Flask development server with reload enabled. Set the environment variable DEBUG_METRICS=1 to enable them anyway.
2025-07-25 09:16:57,614 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:16:57,614 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:17:10,204 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:17:10,256 INFO werkzeug:  * Restarting with stat
2025-07-25 09:17:10,643 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:17:10,643 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:17:14,901 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:17:14,949 INFO werkzeug:  * Restarting with stat
2025-07-25 09:17:15,302 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:17:15,303 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:17:23,715 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:17:23,759 INFO werkzeug:  * Restarting with stat
2025-07-25 09:17:24,126 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:17:24,127 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:17:27,338 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:17:27,386 INFO werkzeug:  * Restarting with stat
2025-07-25 09:17:27,750 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:17:27,751 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:18:13,803 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:18:13,867 INFO werkzeug:  * Restarting with stat
2025-07-25 09:18:14,279 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:18:14,280 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:01,920 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:01,966 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:02,311 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:02,311 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:05,523 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:05,569 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:05,932 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:05,932 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:09,142 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:09,184 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:09,565 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:09,565 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:10,713 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:10,769 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:11,190 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:11,191 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:18,579 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:18,642 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:19,038 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:19,039 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:21,193 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:21,234 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:21,582 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:21,582 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:24,796 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:24,845 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:25,191 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:25,192 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:28,411 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:28,464 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:28,838 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:28,838 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:32,036 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:32,079 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:32,446 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:32,446 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:33,584 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:33,630 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:33,985 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:33,986 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:37,203 INFO werkzeug:  * Detected change in '/app/utils/matrics_utils.py', reloading
2025-07-25 09:20:37,259 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:37,609 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:37,610 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:20:55,509 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:20:55,569 INFO werkzeug:  * Restarting with stat
2025-07-25 09:20:56,042 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:20:56,043 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:21:02,450 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:21:02,512 INFO werkzeug:  * Restarting with stat
2025-07-25 09:21:02,925 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:21:02,926 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:21:04,077 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:21:04,160 INFO werkzeug:  * Restarting with stat
2025-07-25 09:21:04,586 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:21:04,586 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:21:05,723 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:21:05,789 INFO werkzeug:  * Restarting with stat
2025-07-25 09:21:06,237 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:21:06,238 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:21:09,712 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:21:09] "GET /mathSolve/metrics HTTP/1.1" 200 -
2025-07-25 09:21:09,749 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:21:09] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-25 09:21:24,678 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:21:24] "GET /mathSolve/metrics HTTP/1.1" 200 -
2025-07-25 09:21:24,719 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 09:21:24] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-25 09:37:26,586 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:37:26,752 INFO werkzeug:  * Restarting with stat
2025-07-25 09:37:27,595 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:37:27,596 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:40:50,680 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:40:50,744 INFO werkzeug:  * Restarting with stat
2025-07-25 09:40:51,151 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:40:51,151 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:40:58,555 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:40:58,604 INFO werkzeug:  * Restarting with stat
2025-07-25 09:40:58,990 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:40:58,991 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 09:41:04,311 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 09:41:04,359 INFO werkzeug:  * Restarting with stat
2025-07-25 09:41:04,765 WARNING werkzeug:  * Debugger is active!
2025-07-25 09:41:04,766 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 11:36:47,836 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.5:5000
2025-07-25 11:36:47,837 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 11:36:47,838 INFO werkzeug:  * Restarting with stat
2025-07-25 11:36:48,280 WARNING werkzeug:  * Debugger is active!
2025-07-25 11:36:48,281 INFO werkzeug:  * Debugger PIN: 100-767-306
2025-07-25 11:40:44,424 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2025-07-25 11:40:44,425 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 11:40:44,428 INFO werkzeug:  * Restarting with stat
2025-07-25 11:40:44,923 WARNING werkzeug:  * Debugger is active!
2025-07-25 11:40:44,924 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 11:41:47,341 INFO werkzeug:  * Detected change in '/app/utils/kafka_logger.py', reloading
2025-07-25 11:41:47,438 INFO werkzeug:  * Restarting with stat
2025-07-25 11:41:47,871 WARNING werkzeug:  * Debugger is active!
2025-07-25 11:41:47,872 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 11:58:11,140 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
2025-07-25 11:58:11,140 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 11:58:11,146 INFO werkzeug:  * Restarting with stat
2025-07-25 11:58:11,615 WARNING werkzeug:  * Debugger is active!
2025-07-25 11:58:11,616 INFO werkzeug:  * Debugger PIN: 376-664-055
2025-07-25 12:01:05,703 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2025-07-25 12:01:05,703 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 12:01:05,706 INFO werkzeug:  * Restarting with stat
2025-07-25 12:01:06,443 WARNING werkzeug:  * Debugger is active!
2025-07-25 12:01:06,445 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 12:08:00,612 INFO werkzeug:  * Detected change in '/app/controller/login_controller.py', reloading
2025-07-25 12:08:00,700 INFO werkzeug:  * Restarting with stat
2025-07-25 12:08:01,347 WARNING werkzeug:  * Debugger is active!
2025-07-25 12:08:01,348 INFO werkzeug:  * Debugger PIN: 170-333-443
2025-07-25 12:08:04,576 INFO werkzeug:  * Detected change in '/app/controller/login_controller.py', reloading
2025-07-25 12:08:04,638 INFO werkzeug:  * Restarting with stat
2025-07-25 12:48:34,484 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 12:48:34,484 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 12:48:34,485 INFO werkzeug:  * Restarting with stat
2025-07-25 12:48:34,928 WARNING werkzeug:  * Debugger is active!
2025-07-25 12:48:34,929 INFO werkzeug:  * Debugger PIN: 668-044-847
2025-07-25 12:48:51,905 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 12:48:51] "GET /mathSolve/welcome HTTP/1.1" 200 -
2025-07-25 12:48:53,025 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 12:48:53] "GET /mathSolve/login HTTP/1.1" 200 -
2025-07-25 12:49:12,904 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 12:49:12,905 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 12:49:12,906 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 12:49:12,947 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-25 12:49:13,077 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-25 12:49:13,080 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 12:49:13] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-25 12:49:13,128 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 12:49:13] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 12:53:34,424 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 12:53:34,425 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 12:53:34,426 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 12:55:02,343 INFO werkzeug:  * Detected change in '/app/utils/kafka_consumer_thread.py', reloading
2025-07-25 12:55:02,414 INFO werkzeug:  * Restarting with stat
2025-07-25 12:55:03,005 WARNING werkzeug:  * Debugger is active!
2025-07-25 12:55:03,006 INFO werkzeug:  * Debugger PIN: 668-044-847
2025-07-25 12:55:04,132 INFO werkzeug:  * Detected change in '/app/utils/kafka_consumer_thread.py', reloading
2025-07-25 12:55:04,183 INFO werkzeug:  * Restarting with stat
2025-07-25 12:55:04,611 WARNING werkzeug:  * Debugger is active!
2025-07-25 12:55:04,612 INFO werkzeug:  * Debugger PIN: 668-044-847
2025-07-25 12:58:15,012 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 12:58:15,079 INFO werkzeug:  * Restarting with stat
2025-07-25 12:58:15,724 WARNING werkzeug:  * Debugger is active!
2025-07-25 12:58:15,725 INFO werkzeug:  * Debugger PIN: 668-044-847
2025-07-25 12:58:16,563 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 12:58:16,564 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 12:58:16,564 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 12:58:16,565 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 12:58:16,565 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 12:58:16,566 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 12:58:16,566 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 12:58:16,667 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 12:58:16,685 INFO kafka.coordinator: Received member id kafka-python-2.2.15-f652e58e-bdbd-49ac-96f1-7e2427d745ff for group log-viewer; will retry join-group
2025-07-25 12:58:16,686 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 12:58:16,686 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 12:58:18,979 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 12:58:19,055 INFO werkzeug:  * Restarting with stat
2025-07-25 12:58:19,551 WARNING werkzeug:  * Debugger is active!
2025-07-25 12:58:19,551 INFO werkzeug:  * Debugger PIN: 668-044-847
2025-07-25 12:58:19,618 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 12:58:19,619 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 12:58:19,619 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 12:58:19,620 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 12:58:19,620 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 12:58:19,622 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 12:58:19,622 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 12:58:19,723 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 12:58:19,725 INFO kafka.coordinator: Received member id kafka-python-2.2.15-a308e9fc-87a1-4075-b6ce-f2e7ce48926b for group log-viewer; will retry join-group
2025-07-25 12:58:19,725 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 12:58:19,726 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:17:32,243 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 13:17:32,243 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:17:32,244 INFO werkzeug:  * Restarting with stat
2025-07-25 13:17:32,276 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 13:17:32,277 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 13:17:32,277 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 13:17:32,278 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:17:32,279 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 13:17:32,280 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:17:32,281 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:17:32,382 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:17:32,396 INFO kafka.coordinator: Received member id kafka-python-2.2.15-1a41e198-1a12-49b0-bcfc-afe87fff870b for group log-viewer; will retry join-group
2025-07-25 13:17:32,397 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 13:17:32,397 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:17:32,672 WARNING werkzeug:  * Debugger is active!
2025-07-25 13:17:32,673 INFO werkzeug:  * Debugger PIN: 668-044-847
2025-07-25 13:17:32,743 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 13:17:32,744 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 13:17:32,744 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 13:17:32,745 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:17:32,745 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 13:17:32,746 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:17:32,746 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:17:32,847 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:17:32,851 INFO kafka.coordinator: Received member id kafka-python-2.2.15-63a6e64e-f5f0-40a2-83fe-0b3bea16c00f for group log-viewer; will retry join-group
2025-07-25 13:17:32,851 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 13:17:32,852 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:17:38,416 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 1 (member_id: kafka-python-2.2.15-1a41e198-1a12-49b0-bcfc-afe87fff870b, protocol: range)>
2025-07-25 13:17:38,417 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 1 (member_id: kafka-python-2.2.15-63a6e64e-f5f0-40a2-83fe-0b3bea16c00f, protocol: range)>
2025-07-25 13:17:38,417 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:17:38,452 INFO kafka.consumer.subscription_state: Updated partition assignment: []
2025-07-25 13:17:38,452 INFO kafka.consumer.subscription_state: Updated partition assignment: [TopicPartition(topic='logs', partition=0)]
2025-07-25 13:17:38,452 INFO kafka.coordinator.consumer: Setting newly assigned partitions set() for group log-viewer
2025-07-25 13:17:38,452 INFO kafka.coordinator.consumer: Setting newly assigned partitions {TopicPartition(topic='logs', partition=0)} for group log-viewer
2025-07-25 13:17:38,467 INFO kafka.consumer.fetcher: Resetting offset for partition TopicPartition(topic='logs', partition=0) to offset 0.
2025-07-25 13:22:32,178 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:22:32,179 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:22:32,180 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:22:32,634 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:22:32,635 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:22:32,636 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:26:33,366 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.5:5000
2025-07-25 13:26:33,367 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:26:33,368 INFO werkzeug:  * Restarting with stat
2025-07-25 13:26:33,813 WARNING werkzeug:  * Debugger is active!
2025-07-25 13:26:33,813 INFO werkzeug:  * Debugger PIN: 100-767-306
2025-07-25 13:26:36,093 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:26:36,094 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:26:36,095 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:26:36,467 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:26:36,468 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:26:36,469 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:28:29,200 INFO werkzeug:  * Detected change in '/app/utils/kafka_consumer_thread.py', reloading
2025-07-25 13:28:29,257 INFO werkzeug:  * Restarting with stat
2025-07-25 13:28:29,878 WARNING werkzeug:  * Debugger is active!
2025-07-25 13:28:29,879 INFO werkzeug:  * Debugger PIN: 100-767-306
2025-07-25 13:28:32,616 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:28:32,617 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:28:32,618 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:28:37,312 INFO werkzeug:  * Detected change in '/app/utils/kafka_consumer_thread.py', reloading
2025-07-25 13:28:37,384 INFO werkzeug:  * Restarting with stat
2025-07-25 13:28:37,789 WARNING werkzeug:  * Debugger is active!
2025-07-25 13:28:37,790 INFO werkzeug:  * Debugger PIN: 100-767-306
2025-07-25 13:28:40,539 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:28:40,540 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:28:40,541 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:28:45,198 INFO werkzeug:  * Detected change in '/app/utils/kafka_consumer_thread.py', reloading
2025-07-25 13:28:45,261 INFO werkzeug:  * Restarting with stat
2025-07-25 13:28:45,724 WARNING werkzeug:  * Debugger is active!
2025-07-25 13:28:45,724 INFO werkzeug:  * Debugger PIN: 100-767-306
2025-07-25 13:28:48,476 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:28:48,476 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:28:48,477 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:28:56,260 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:28:56,261 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:28:56,261 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:29:04,038 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:29:04,039 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:29:04,039 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:29:11,825 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:29:11,825 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:29:11,826 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:29:19,605 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:29:19,606 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:29:19,606 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:29:27,384 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:29:27,384 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:29:27,385 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:29:35,180 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:29:35,181 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:29:35,181 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:29:41,302 INFO werkzeug:  * Detected change in '/app/main.py', reloading
2025-07-25 13:29:41,385 INFO werkzeug:  * Restarting with stat
2025-07-25 13:29:44,048 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:29:44,048 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:29:44,049 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:29:53,863 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 13:29:53,864 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:29:53,885 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:29:53,886 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:29:53,886 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:29:53,886 WARNING kafka.client: No node available during check_version; sleeping 0.11 secs
2025-07-25 13:29:53,996 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:29:53,997 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:29:53,998 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:29:53,998 WARNING kafka.client: No node available during check_version; sleeping 0.24 secs
2025-07-25 13:29:54,237 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:29:54,238 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:29:54,239 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:29:54,240 WARNING kafka.client: No node available during check_version; sleeping 0.47 secs
2025-07-25 13:29:54,707 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:29:54,707 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:29:54,708 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:29:54,709 WARNING kafka.client: No node available during check_version; sleeping 0.80 secs
2025-07-25 13:29:55,508 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:29:55,508 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:29:55,509 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:29:55,509 WARNING kafka.client: No node available during check_version; sleeping 0.32 secs
2025-07-25 13:30:00,834 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:30:00,843 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
2025-07-25 13:30:00,844 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:30:00,845 INFO kafka.consumer.subscription_state: Updating subscribed topics to: ('logs',)
2025-07-25 13:30:00,856 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:30:00,857 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:30:00,858 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:30:00,962 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 13:30:00,963 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 13:30:00,964 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 13:30:00,965 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:30:00,965 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 13:30:00,966 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:30:00,967 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:30:01,068 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:30:01,079 INFO kafka.coordinator: Received member id kafka-python-2.2.15-d577bbc7-80fc-43dc-9804-9738863c8f4a for group log-viewer; will retry join-group
2025-07-25 13:30:01,080 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 13:30:01,080 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:30:07,121 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 2 (member_id: kafka-python-2.2.15-d577bbc7-80fc-43dc-9804-9738863c8f4a, protocol: range)>
2025-07-25 13:30:07,121 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:30:07,159 INFO kafka.consumer.subscription_state: Updated partition assignment: [TopicPartition(topic='logs', partition=0)]
2025-07-25 13:30:07,160 INFO kafka.coordinator.consumer: Setting newly assigned partitions {TopicPartition(topic='logs', partition=0)} for group log-viewer
2025-07-25 13:31:34,154 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:34] "[32mGET /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-25 13:31:36,210 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:36] "[32mGET /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-25 13:31:36,265 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:36] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 13:31:41,865 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:41] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-07-25 13:31:52,846 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:52] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-07-25 13:31:52,885 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:52] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-07-25 13:31:54,333 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:54] "GET /mathSolve/login HTTP/1.1" 200 -
2025-07-25 13:31:54,365 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:54] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-07-25 13:31:54,832 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:54] "[36mGET /mathSolve/login HTTP/1.1[0m" 304 -
2025-07-25 13:31:54,860 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:54] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
2025-07-25 13:31:58,154 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:31:58] "[33mGET /welcome HTTP/1.1[0m" 404 -
2025-07-25 13:32:44,758 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:32:44] "GET /mathSolve/login HTTP/1.1" 200 -
2025-07-25 13:32:51,628 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:32:51,635 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
2025-07-25 13:32:51,635 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:32:51,739 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:32:51,740 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:32:51,741 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:32:51,757 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-25 13:32:51,871 INFO root: Login SUCCESS for daria.craciun411@gmail.com
2025-07-25 13:32:51,874 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:32:51] "[32mPOST /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-25 13:32:51,887 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:32:51] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 13:34:44,163 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 13:34:44,164 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:34:44,186 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:34:44,187 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:34:44,187 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:34:44,188 WARNING kafka.client: No node available during check_version; sleeping 0.08 secs
2025-07-25 13:34:44,273 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:34:44,273 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:34:44,274 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:34:44,274 WARNING kafka.client: No node available during check_version; sleeping 0.16 secs
2025-07-25 13:34:44,440 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:34:44,440 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:34:44,441 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:34:44,441 WARNING kafka.client: No node available during check_version; sleeping 0.48 secs
2025-07-25 13:34:44,918 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:34:44,919 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:34:44,919 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:34:44,920 WARNING kafka.client: No node available during check_version; sleeping 0.69 secs
2025-07-25 13:34:45,614 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:34:45,614 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:34:45,615 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:34:45,616 WARNING kafka.client: No node available during check_version; sleeping 0.51 secs
2025-07-25 13:34:53,918 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:34:53,919 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:34:53,920 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:35:01,698 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:35:01,698 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:35:01,699 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:35:09,476 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:35:09,477 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:35:09,478 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:35:28,497 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 13:35:28,498 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:35:28,511 WARNING kafka.cluster: Topic logs is not available during auto-create initialization
2025-07-25 13:35:28,513 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:35:28,519 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:35:28,519 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:35:29,269 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 13:35:29,270 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 13:35:29,270 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 13:35:29,271 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:35:29,271 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 13:35:29,272 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:35:29,273 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:35:29,373 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:35:29,386 INFO kafka.coordinator: Received member id kafka-python-2.2.15-f5a6aa9b-3358-4535-976a-65c9c5052063 for group log-viewer; will retry join-group
2025-07-25 13:35:29,387 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 13:35:29,387 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:35:32,402 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 1 (member_id: kafka-python-2.2.15-f5a6aa9b-3358-4535-976a-65c9c5052063, protocol: range)>
2025-07-25 13:35:32,403 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:35:32,403 WARNING kafka.coordinator.assignors.range: No partition metadata for topic logs
2025-07-25 13:35:32,440 INFO kafka.consumer.subscription_state: Updated partition assignment: []
2025-07-25 13:35:32,440 INFO kafka.coordinator.consumer: Setting newly assigned partitions set() for group log-viewer
2025-07-25 13:35:35,441 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:35:35,446 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:35:35,449 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 2 (member_id: kafka-python-2.2.15-f5a6aa9b-3358-4535-976a-65c9c5052063, protocol: range)>
2025-07-25 13:35:35,449 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:35:35,453 INFO kafka.consumer.subscription_state: Updated partition assignment: [TopicPartition(topic='logs', partition=0)]
2025-07-25 13:35:35,453 INFO kafka.coordinator.consumer: Setting newly assigned partitions {TopicPartition(topic='logs', partition=0)} for group log-viewer
2025-07-25 13:35:35,469 INFO kafka.consumer.fetcher: Resetting offset for partition TopicPartition(topic='logs', partition=0) to offset 0.
2025-07-25 13:35:52,389 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:35:52] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 13:35:54,793 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:35:54,797 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
2025-07-25 13:35:54,797 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:35:54,901 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:35:54,903 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:35:54,904 INFO kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:35:54,919 INFO root: Login attempt for daria.craciun411@gmail.com
2025-07-25 13:35:54,926 ERROR main: Exception on /mathSolve/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 772, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Table 'mathdb.USERS' doesn't exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/routes/auth_routes.py", line 18, in login_post
    result = login_controller_instance.login(email, password)
  File "/app/controller/login_controller.py", line 15, in login
    user = user_model.get_user_by_email(self.cursor, email)
  File "/app/model/user_model.py", line 3, in get_user_by_email
    cursor.execute("SELECT * FROM USERS WHERE email = %s", (email,))
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/cursor_cext.py", line 353, in execute
    self._connection.cmd_query(
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 781, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'mathdb.USERS' doesn't exist
2025-07-25 13:35:54,975 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:35:54] "[35m[1mPOST /mathSolve/login HTTP/1.1[0m" 500 -
2025-07-25 13:36:04,989 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:36:04] "[32mGET /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-25 13:37:28,830 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:37:28] "[33mGET /mathSolve/matrics HTTP/1.1[0m" 404 -
2025-07-25 13:37:33,716 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:37:33] "GET /mathSolve/metrics HTTP/1.1" 200 -
2025-07-25 13:42:34,615 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:42:34] "[33mGET /kafka-logs HTTP/1.1[0m" 404 -
2025-07-25 13:42:57,782 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 13:42:57,782 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:42:57,800 WARNING kafka.cluster: Topic logs is not available during auto-create initialization
2025-07-25 13:42:57,801 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:42:57,802 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:42:57,802 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:42:58,559 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 13:42:58,560 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 13:42:58,560 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 13:42:58,561 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:42:58,561 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 13:42:58,563 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:42:58,564 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:42:58,665 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:42:58,677 INFO kafka.coordinator: Received member id kafka-python-2.2.15-da91eba3-c97d-4eab-8283-7e67e4799f9f for group log-viewer; will retry join-group
2025-07-25 13:42:58,677 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 13:42:58,678 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:43:01,696 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 1 (member_id: kafka-python-2.2.15-da91eba3-c97d-4eab-8283-7e67e4799f9f, protocol: range)>
2025-07-25 13:43:01,698 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:43:01,699 WARNING kafka.coordinator.assignors.range: No partition metadata for topic logs
2025-07-25 13:43:01,740 INFO kafka.consumer.subscription_state: Updated partition assignment: []
2025-07-25 13:43:01,741 INFO kafka.coordinator.consumer: Setting newly assigned partitions set() for group log-viewer
2025-07-25 13:43:04,743 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:43:04,747 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:43:04,751 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 2 (member_id: kafka-python-2.2.15-da91eba3-c97d-4eab-8283-7e67e4799f9f, protocol: range)>
2025-07-25 13:43:04,751 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:43:04,756 INFO kafka.consumer.subscription_state: Updated partition assignment: [TopicPartition(topic='logs', partition=0)]
2025-07-25 13:43:04,756 INFO kafka.coordinator.consumer: Setting newly assigned partitions {TopicPartition(topic='logs', partition=0)} for group log-viewer
2025-07-25 13:43:04,773 INFO kafka.consumer.fetcher: Resetting offset for partition TopicPartition(topic='logs', partition=0) to offset 0.
2025-07-25 13:43:35,033 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:43:35] "[36mGET /mathSolve/welcome HTTP/1.1[0m" 304 -
2025-07-25 13:43:36,810 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:43:36] "[32mGET /mathSolve/login HTTP/1.1[0m" 302 -
2025-07-25 13:43:36,823 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:43:36] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 13:45:38,006 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:45:38] "[33mGET /mathSolve/kafka-logs HTTP/1.1[0m" 404 -
2025-07-25 13:45:41,509 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:45:41] "[33mGET /mathSolve/kafka-logs HTTP/1.1[0m" 404 -
2025-07-25 13:46:59,049 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 13:46:59,050 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:46:59,080 WARNING kafka.cluster: Topic logs is not available during auto-create initialization
2025-07-25 13:46:59,081 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:46:59,082 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:46:59,083 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:46:59,954 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 13:46:59,955 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 13:46:59,955 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 13:46:59,956 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:46:59,956 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 13:46:59,957 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:46:59,958 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:47:00,059 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:47:00,075 INFO kafka.coordinator: Received member id kafka-python-2.2.15-1184e654-c0bc-413c-a834-25bb9d752015 for group log-viewer; will retry join-group
2025-07-25 13:47:00,076 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 13:47:00,076 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:47:03,097 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 1 (member_id: kafka-python-2.2.15-1184e654-c0bc-413c-a834-25bb9d752015, protocol: range)>
2025-07-25 13:47:03,097 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:47:03,098 WARNING kafka.coordinator.assignors.range: No partition metadata for topic logs
2025-07-25 13:47:03,139 INFO kafka.consumer.subscription_state: Updated partition assignment: []
2025-07-25 13:47:03,139 INFO kafka.coordinator.consumer: Setting newly assigned partitions set() for group log-viewer
2025-07-25 13:47:06,142 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:47:06,146 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:47:06,150 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 2 (member_id: kafka-python-2.2.15-1184e654-c0bc-413c-a834-25bb9d752015, protocol: range)>
2025-07-25 13:47:06,150 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:47:06,155 INFO kafka.consumer.subscription_state: Updated partition assignment: [TopicPartition(topic='logs', partition=0)]
2025-07-25 13:47:06,155 INFO kafka.coordinator.consumer: Setting newly assigned partitions {TopicPartition(topic='logs', partition=0)} for group log-viewer
2025-07-25 13:47:06,175 INFO kafka.consumer.fetcher: Resetting offset for partition TopicPartition(topic='logs', partition=0) to offset 0.
2025-07-25 13:47:12,566 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:47:12] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 13:52:21,682 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 13:52:21,683 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:52:21,691 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:52:21,692 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:52:21,692 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:52:21,693 WARNING kafka.client: No node available during check_version; sleeping 0.09 secs
2025-07-25 13:52:21,785 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:52:21,786 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:52:21,786 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:52:21,787 WARNING kafka.client: No node available during check_version; sleeping 0.16 secs
2025-07-25 13:52:21,950 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:52:21,951 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:52:21,952 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:52:21,952 WARNING kafka.client: No node available during check_version; sleeping 0.37 secs
2025-07-25 13:52:22,319 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:52:22,320 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:52:22,320 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:52:22,321 WARNING kafka.client: No node available during check_version; sleeping 0.89 secs
2025-07-25 13:52:23,211 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:52:23,219 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-07-25 13:52:23,219 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-07-25 13:52:23,220 WARNING kafka.client: No node available during check_version; sleeping 0.43 secs
2025-07-25 13:52:31,440 WARNING kafka.conn: DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
2025-07-25 13:52:31,441 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
2025-07-25 13:52:31,442 ERROR kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
2025-07-25 13:52:49,071 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.6:5000
2025-07-25 13:52:49,071 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-07-25 13:52:49,121 WARNING kafka.cluster: Topic logs is not available during auto-create initialization
2025-07-25 13:52:49,123 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:52:49,124 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:52:49,125 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
2025-07-25 13:52:50,008 INFO kafka.cluster: Coordinator for group/log-viewer is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=9092, rack=None)
2025-07-25 13:52:50,008 INFO kafka.coordinator: Discovered coordinator coordinator-1 for group log-viewer
2025-07-25 13:52:50,009 INFO kafka.coordinator.heartbeat: Starting new heartbeat thread
2025-07-25 13:52:50,009 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:52:50,010 INFO kafka.coordinator: Failed to join group log-viewer: NodeNotReadyError: coordinator-1
2025-07-25 13:52:50,011 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
2025-07-25 13:52:50,011 INFO kafka.conn: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
2025-07-25 13:52:50,112 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:52:50,130 INFO kafka.coordinator: Received member id kafka-python-2.2.15-208393e4-916e-4778-80e8-ad6ac68caa5c for group log-viewer; will retry join-group
2025-07-25 13:52:50,131 INFO kafka.coordinator: Failed to join group log-viewer: [Error 79] MemberIdRequiredError
2025-07-25 13:52:50,132 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:52:53,154 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 1 (member_id: kafka-python-2.2.15-208393e4-916e-4778-80e8-ad6ac68caa5c, protocol: range)>
2025-07-25 13:52:53,154 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:52:53,155 WARNING kafka.coordinator.assignors.range: No partition metadata for topic logs
2025-07-25 13:52:53,198 INFO kafka.consumer.subscription_state: Updated partition assignment: []
2025-07-25 13:52:53,199 INFO kafka.coordinator.consumer: Setting newly assigned partitions set() for group log-viewer
2025-07-25 13:52:56,202 INFO kafka.coordinator.consumer: Revoking previously assigned partitions set() for group log-viewer
2025-07-25 13:52:56,205 INFO kafka.coordinator: (Re-)joining group log-viewer
2025-07-25 13:52:56,209 INFO kafka.coordinator: Successfully joined group log-viewer <Generation 2 (member_id: kafka-python-2.2.15-208393e4-916e-4778-80e8-ad6ac68caa5c, protocol: range)>
2025-07-25 13:52:56,209 INFO kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-07-25 13:52:56,214 INFO kafka.consumer.subscription_state: Updated partition assignment: [TopicPartition(topic='logs', partition=0)]
2025-07-25 13:52:56,214 INFO kafka.coordinator.consumer: Setting newly assigned partitions {TopicPartition(topic='logs', partition=0)} for group log-viewer
2025-07-25 13:52:56,237 INFO kafka.consumer.fetcher: Resetting offset for partition TopicPartition(topic='logs', partition=0) to offset 0.
2025-07-25 13:53:06,040 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:53:06] "[36mGET /mathSolve/calculator HTTP/1.1[0m" 304 -
2025-07-25 13:53:11,952 INFO werkzeug: 192.168.143.2 - - [25/Jul/2025 13:53:11] "GET /mathSolve/kafka-logs HTTP/1.1" 200 -
